name: Generate Pluto US EPG

on:
  workflow_dispatch:
  schedule:
    # 12:00 AM AST (04:00 UTC)
    - cron: "0 4 * * *"
    # 12:00 PM AST (16:00 UTC)
    - cron: "0 16 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create XMLTV folder
        run: mkdir -p XMLTV

      - name: Generate Pluto US XMLTV
        run: npm run grab -- --channels=sites/pluto.tv/pluto.tv_us.channels.xml --output=XMLTV/pluto_us.xml

      - name: Commit updated XML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add XMLTV/pluto_us.xml

          git diff --cached --quiet || git commit -m "Update Pluto US EPG"

          git push
